0x01-challenge/blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :installs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'
end

0x01-challenge/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

0x01-challenge/blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

0x01-challenge/blog/app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

0x01-challenge/blog/app/models/post.rb
class Post < ApplicationRecord
  has_many  :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

0x01-challenge/blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

0x01-challenge/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

0x01-challenge/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

0x01-challenge/blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

0x01-challenge/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

0x01-challenge/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

0x01-challenge/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

0x01-challenge/blog/app/helpers/posts_helper.rb
module PostsHelper
end

0x01-challenge/blog/app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? %>
	<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: 'Are you sure?' } %></p>
	<% end %>
</div>

0x01-challenge/blog/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>
<br>
<p>
  <%= f.submit %>
</p>
<% end %>

0x01-challenge/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.svg" %>
        <% end %>
      </div>

      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
      <% end %>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>All Posts</p>
        <% elsif current_page?(about_path) %>
          <p>About</p>
        <% else %>
          <%= link_to "Back to All Posts", root_path %>
        <% end %>

        <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button"><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></button>

        </div>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end %>

      <%= yield %>

    </div>
  </body>
</html>

0x01-challenge/blog/app/views/pages/about.html.erb
<div id="page_wrapper">
	
</div>

0x01-challenge/blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

0x01-challenge/blog/app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>

</div>

0x01-challenge/blog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
  <h2 class="title"><%= link_to post.title, post %></h2>
  <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>
<% end %>

0x01-challenge/blog/app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>

  <%= render 'form' %>

</div>

0x01-challenge/blog/app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
    | <%= link_to 'Edit', edit_post_path(@post) %>
    | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment :</h3>
    <%= render "comments/form" %>
  </div>
</div>